# linuxkit build template 
#
# Copyright (c) 2018 Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
org: lfedge
image: eve-storage-init
network: yes
net: host
pid: host
config:
  binds:
    - /media/root-ro:/root:rshared,rbind
    - /media/boot:/bits:rshared,rbind
    - /lib/modules:/lib/modules:rshared,rbind,rw
 # from storage-init 
    - /:/hostfs
    - /lib/modules:/lib/modules
    - /dev:/dev
    - /run:/run
    - /var:/var
    - /persist:/persist:rshared,rbind
    - /config:/config:rshared,rbind
    - /containers:/containers:rshared,rbind
  rootfsPropagation: shared
  capabilities:
    - all
