# Copyright (c) 2022 Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0

org: lfedge
image: eve-installer
network: yes
config:
  pid: host
  binds:
    - /:/hostfs
    - /lib/modules:/lib/modules
    - /dev:/dev
    - /run:/run
    - /var:/var
    - /persist:/persist:rshared,rbind
    - /config:/config:rshared,rbind
    - /containers:/containers:rshared,rbind
    # this one doesn't exist if we run 'live'
    #- /media/boot:/bits:rshared,rbind
    - /opt/zededa:/containers/services/pillar/lower/opt/zededa:rshared,rbind,rw
    #- /opt/debug:/containers/services/debug/lower:rshared,rbind,rw
  capabilities:
    - all
  rootfsPropagation: shared