org: lfedge
image: eve-installer
#network: true
config: 
  pid: host
  net: host
  capabilities:
    - all
  tmpfs:
    - /persit:rw
    - /tmp:noexec
    - /efifs:noexec
  binds:
    - /:/hostfs
    - /lib/modules:/lib/modules
    - /dev:/dev
    - /run:/run
    - /var:/var
    - /persist:/persist:rshared,rbind
    - /config:/config:rshared,rbind
    - /containers:/containers:rshared,rbind
  rootfsPropagation: shared
  devices:
  # individual console / tty character devices
  - path: "/dev/console"
    type: c
    major: 5
    minor: 1
    mode: 0666
  - path: "/dev/tty0"
    type: c
    major: 4
    minor: 0
    mode: 0666
  - path: "/dev/ttyS0"
    type: c
    major: 4
    minor: 64
    mode: 0666
  - path: "/dev/ttyAMA0"
    type: c
    major: 204
    minor: 64
    mode: 0666
